import Head from "next/head";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

function Layout({ children, menuItems }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header menuItems={menuItems}></Header>

      <main>{children}</main>

      <Footer></Footer>
    </>
  );
}

export default Layout;
